@startuml
class Estudiante {
  - Long id
  - String nombre
  - String correo
  - String telefono
  - String idioma
}
class EstudianteRepo
class EstudianteService
class EstudianteController
EstudianteController --> EstudianteService
EstudianteService --> EstudianteRepo
@enduml
